baseURL = 'http://www.vemiller.com/'
languageCode = 'en-us'
title = 'Nuts and Bolts'
theme = "hugo-kiera"

[params]
  author = "Vaughn Miller"
  tagline = "Some things I've learned along the way..."
  copyright = "Copyright &copy; 2022 - Vaughn Miller"
  disableDarkModeCSS = false

[permalinks]
	posts = '/:year/:month/:day/:title'

[author]
    name = "Vaughn Miller"           #Author name
    github = "vmiller"         #Github username
    linkedin = "vaughn-miller-a4799742"       #LinkedIn username
    twitter = "Vaughn_E_Miller"        #Twitter username

[Menus]
  main = [
  	{Name = "Github", URL = "https://github.com/vmiller/"},
  	{Name = "Twitter", URL = "https://twitter.com/Vaughn_E_Miller"},
  	{Name = "LinkedIn", URL = "https://www.linkedin.com/in/vaughn-miller-a4799742/"}
  	]